
# создать папку для приложения, если не существует /opt/app
- name: "Create app directory - {{ app_work_directory }}"
  ansible.builtin.file:
    path: "{{ app_work_directory }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: "0755"


# скопировать папку с приложением в /opt/app
- name: "Copy applications files into {{ app_work_directory }}"
  ansible.builtin.copy:
    src: files/
    dest: "{{ app_work_directory }}/"
    owner: vagrant
    group: vagrant
    mode: '0644'


- name: "Istall dependencies"
  # become: no
  ansible.builtin.shell: 
    cmd: |
      gem install bundler -v 1.16.2
      bundle config build.nokogiri --use-system-libraries
      bundle install --clean  --no-cache --without development
    chdir: "{{ app_work_directory }}"
  args:
    warn: no

  ignore_errors: yes
  


# скопировать из шаблона сервис systemd
- name: "Copy service file"
  ansible.builtin.template:
    src: ruby-app.service.j2
    dest: "/etc/systemd/system/{{ app_name }}.service"
    owner: vagrant
    group: vagrant
    mode: "0644"

# включить сервис и включить автозагрузку
- name: "Service start"
  ansible.builtin.service:
    name: "{{ app_name }}"
    state: started
    enabled: yes