---
# tasks file for ruby-app

- name: "Tasks with set env"
  include_tasks: install_environment.yml

- name: "Tasks with install NodeJS"
  include_tasks: install_nodejs.yml

- name: "Tasks with install Ruby"
  import_tasks: install_ruby.yml

- name: "Tasks with install ruby application"
  include_tasks: install_app.yml


# # скопировать из шаблона сервис systemd
# - name: "Copy service file"
#   ansible.builtin.template:
#     src: ruby-app.service.j2
#     dest: "/etc/systemd/system/{{ app_name }}.service"
#     owner: vagrant
#     group: vagrant
#     mode: "0644"

# # включить сервис и включить автозагрузку
# - name: "Service start"
#   ansible.builtin.service:
#     name: "{{ app_name }}"
#     state: started
#     enabled: yes